[project]
name = "clinical-triage-mlops"
version = "0.1.0"
description = "Sistema de triagem clínica baseado em aprendizado de máquina para o hospital [1, 2]."
readme = "README.md"
requires-python = ">=3.12,<3.13"

# Dependências MÍNIMAS de produção (apenas o necessário para a API rodar no Docker)
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "pydantic>=2.6.0",
    "pandas>=2.2.0",
    "scikit-learn>=1.4.0" # Necessário para carregar e executar o modelo NLP final [1, 3]
]

# Dependências OPCIONAIS (não entram na imagem Docker da API)
[project.optional-dependencies]
dev = [
    "ruff>=0.3.0",
    "pre-commit>=3.6.0",
    "pytest>=8.0.0"
]
eda = [
    "matplotlib>=3.8.0",
    "seaborn>=0.13.0"
]
orchestration = [
    "apache-airflow>=2.8.0" # O Airflow é gigantesco e roda de forma isolada [3, 4]
]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
# Regras essenciais: Pycodestyle, Pyflakes e Isort para organização automática de imports
select = ["E", "F", "I", "W"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"